/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve044.geometry} material={materials['Material.001']} position={[0.071, 0.491, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/logo.glb')
