export const DB_ID = process.env.NEXT_APPWRITE_DATABASE_ID!;
export const BUCKET_ID = process.env.NEXT_APPWRITE_BUCKET_ID!;

export const COLLECTIONS = {
    MEMBERS: process.env.NEXT_PUBLIC_APPWRITE_MEMBER_COLLECTION_ID!,
    ROLES: process.env.NEXT_PUBLIC_APPWRITE_ROLE_COLLECTION_ID!,
    ORGANIZATIONS: process.env.NEXT_PUBLIC_APPWRITE_ORGANIZATION_COLLECTION_ID!,
    EVENTS: process.env.NEXT_PUBLIC_APPWRITE_EVENTS_COLLECTION_ID!,
    USER_LINK_ROLES: process.env.NEXT_PUBLIC_APPWRITE_USER_LINK_ROLES_COLLECTION_ID!,
    USER_LINK_ORG: process.env.NEXT_PUBLIC_APPWRITE_USER_LINK_ORG_COLLECTION_ID!,
    USER_LINK_SOCIAL: process.env.NEXT_PUBLIC_APPWRITE_USER_LINK_SOCIAL_COLLECTION_ID!,
    EVENT_LINK_ORG: process.env.NEXT_PUBLIC_APPWRITE_EVENT_LINK_ORG_COLLECTION_ID!,
    ACHIEVEMENTS: process.env.NEXT_PUBLIC_APPWRITE_ACHIEVEMENTS_COLLECTION_ID!,
    GALLERY: process.env.NEXT_PUBLIC_APPWRITE_GALLERY_COLLECTION_ID!,
    TIMELINE: process.env.NEXT_PUBLIC_APPWRITE_TIMELINE_COLLECTION_ID!,
    CAMPUS_STATS: process.env.NEXT_PUBLIC_APPWRITE_CAMPUS_STATS_COLLECTION_ID!,
    ACTION_LOGS: process.env.NEXT_PUBLIC_APPWRITE_ACTION_LOGS_COLLECTION_ID!,
} as const;
